(ns new-project.other-programs.Strings)

(defn string-operations []
  (println (str "Hello" "World"))
  (println (format "Hello , %s" "World"))
  (println (count "Hello"))
  (println (subs "HelloWorld" 2 5))
  (println (compare "Hello" "hello"))
  (println (reverse "Hello World"))
  (println (clojure.string/lower-case "HelloWorld"))
  (println (clojure.string/upper-case "HelloWorld"))
  (println (clojure.string/join ", " [1 2 3]))
  (println (clojure.string/split "Hello World" #" "))
  (println (clojure.string/split-lines "Hello\nWorld"))
  (println (clojure.string/replace "The tutorial is about Groovy" #"Groovy" "Clojure"))
  (println (clojure.string/trim " White spaces "))
  (println (clojure.string/triml " White spaces "))
  (println (clojure.string/trimr " White spaces "))
  )
(string-operations)